#ifndef _CODES_H
#define _CODES_H
enum {CON_USR,PRE_BUY_MOVIE,BUY_MOVIE,PRE_CHG_PASS,CHG_PASS,DOWNINFO,DOWNLOAD,DOWNDATA,PRE_LIST_CLIENTS,LIST_CLIENTS,LIST_GEN,LIST_MOVIES,DISCONNECT,HELP,EXIT};
#endif







