.TH msclient 7 "23 de Junio de 2009" "Versión: 1.0"
.SH NAME
msclient - Aplicación para bajar películas
.SH SYNOPSIS
msclient
.SH DESCRIPTION
Esta aplicación se utiliza para comunicarse con un servidor Movie Store, mediante el cual se pueden bajar películas. El usuario debe estar registrado en un servidor de pago y en el servidor LDAP que utiliza el Movie Store Server.
.SH AUTHOR
Gabriel Cosi 47.008, Emmanuel Teisaire 48.019 & Villa Fernández Santiago 47.399