.TH msserver 7 "23 de Junio de 2009" "Versión: 1.0"
.SH NAME
msserver - Aplicación servidor que almacena películas para comprar
.SH SYNOPSIS
msserver
.SH DESCRIPTION
Esta aplicación almacena películas para ser descargadas por el Movie Store Client. Debe contar con la información para poder conectarse con un servidor LDAP para validar usuarios y con un Payment Lookup server para poder contactar servidores de pago.
.SH AUTHOR
Gabriel Cosi 47.008, Emmanuel Teisaire 48.019 & Villa Fernández Santiago 47.399