.TH plserver 7 "23 de Junio de 2009" "Versión: 1.0"
.SH NAME
plserver - Aplicación para buscar servidores de pago
.SH SYNOPSIS
plserver [puerto]
.SH DESCRIPTION
Esta aplicación contiene información sobre los servidores de pago, para ser consultada por el Movie Store Server
.SH OPTIONS
[puerto] - Puerto al cual se bindeara el payment lookup server. Si se omite, se bindeará por default al puerto 10539
.SH AUTHOR
Gabriel Cosi 47.008, Emmanuel Teisaire 48.019 & Villa Fernández Santiago 47.399