.TH pserver 7 "23 de Junio de 2009" "Versión: 1.0"
.SH NAME
pserver - Servidor de pago
.SH SYNOPSIS
pserver [puerto]
.SH DESCRIPTION
Esta aplicación contiene información sobre el crédito disponible de sus clientes
.SH OPTIONS
[puerto] - Puerto al cual se bindeará el payment server. Si se omite, se bindeará por default al puerto 10001
.SH AUTHOR
Gabriel Cosi 47.008, Emmanuel Teisaire 48.019 & Villa Fernández Santiago 47.399